name: Release

on:
  push:
    # Build and publish artifacts for a release
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Log into Kubernetes Container Registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login registry.k8s.io -u ${REGISTRY_USER} --password-stdin

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build Release Artifacts
        run: RELEASE_TAG="${{ github.ref_name }}" make release

      - name: Update crds docs
        run: |
          echo "Release Tag: ${{ github.ref_name }}" 
          curl -sSL https://doc.crds.dev/github.com/oracle/cluster-api-provider-oci@${{ github.ref_name }}

      - name: Build and push Docker image
        run: |
          docker build -t registry.k8s.io/${{ env.REGISTRY_NAMESPACE }}/${{ env.REGISTRY_IMAGE }}:${{ env.REGISTRY_TAG }} .
          docker push registry.k8s.io/${{ env.REGISTRY_NAMESPACE }}/${{ env.REGISTRY_IMAGE }}:${{ env.REGISTRY_TAG }}
        env:
          REGISTRY_USER: your-registry-username
          REGISTRY_NAMESPACE: your-registry-namespace
          REGISTRY_IMAGE: your-image-name
          REGISTRY_TAG: ${{ github.ref_name }}

      - uses: actions/upload-artifact@v2
        with:
          name: CAPOCI Artifacts
          path: out/

